name: broker-lead-engine
services:
- name: web
  source_dir: /
  github:
    repo: broker-lead-engine
    branch: main
  run_command: echo "Static site deployment"
  build_command: npm run build
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 8080
  routes:
  - path: /
  static_sites:
  - name: broker-lead-engine-static
    source_dir: dist
    index_document: index.html
    error_document: index.html
    catchall_document: index.html
    output_dir: dist
    build_command: npm run build